### ISSUE TITLE
Optimize default behavior for porosimetry functions

### ISSUE THREAD

**Issue by mdrkok** [PMEAL/porespy#110]
The relative performance of the 'dt' or 'fft' options can make a significant difference on computational effort

**Comment by jgostick** [comment]
I think this is fixed now, no?  I renamed the 'fft' mode to 'hybrid' which means that a dt is used to get the core of the invading phase, then fft based dilation is used to convert it to invading fluid.  This is the default, and I've also made the local thickness function recognize these new arguments as well.  I also made local_thickness use 25 different sizes, instead of using ALL of them like it used to...which I think is what this optimization is referring to.
