### ISSUE TITLE
fix readthedocs build

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#18]
Readthedocs is not working.  It needs to be setup so that certain modules can be installed during build, specifically numpydoc.  This requires enabling virtualenv in the admin section, but this this means that all the requirements of PoreSpy need to be installed into the virtualenv as well.  This requires specifying a conda requirements file, which is where things go off the rails.  

The solution requires add a 'readthedocs.yml' file to the project, and then specifying the required items inside the file.  Anyone with knowledge of this system, or willingness to follow the instructions [here](http://docs.readthedocs.io/en/latest/yaml-config.html) would be appreciated.

**Comment by RodericDay** [comment]
Checking this out.

**Comment by RodericDay** [comment]
Hmmm... I got my repo to generate 1.4MB of docs, in 62 files. No errors. I opened it on Firefox and browsed around a bit, and everything seems to work?

I'm not sure if I'm missing part of it?

I did not require the addition a `readthedocs.yml` file. I simply:

1) Created a `venv`
2) Installed all the requirements from all the `*_requirements.txt` files
3) Installed Sphinx, which was not listed as a requirement?
4) Moved the `makefile` to the root level, because it seemed to not want to be in the `docs` sub-folder (the makefile can easily be modified to be aware of its relative displacement)
5) Called `make html`. First time it raised a few warnings, then I did it again, and it went quietly.

**Comment by RodericDay** [comment]
According to the readthedocs site, generating the _build directory full of HTML files is only half the battle. However, the other half seems to be uploading them to their website, using the username and password associated with your account and so on.

The aforementioned `.yml` file seems like it'd automate things like having to call both `make html` or `make epub`.

All of this to say, I'm not sure I'm understanding/reproducing the issue correctly?

**Comment by jgostick** [comment]
Hey Harold
The point is to get readthedocs to build it automatically.  The docs are [here](http://porespy.readthedocs.io/en/latest/).  I think they're working now.

**Comment by jgostick** [comment]
OK, here's the status...when built locally, all the sphinx directives work and it pulls the docstrings and makes nice module indexes, etc...but when readthedocs builds these things do no work.

**Comment by RodericDay** [comment]
Hmm. I registered an account on readthedocs.io, hooked my repo, and created these: http://porespy-fork.readthedocs.io/en/latest/

I didn't add any yaml file, but I did put all your requirement files in a subdirectory and added a root requirements.txt to reference them.

**Comment by RodericDay** [comment]
Let me know if this doesn't do the trick. I didn't do anything else, my readthedocs.io configs were the basic defaults.

**Comment by RodericDay** [comment]
To be clear, I do not use the virtualenv at all. All the fields in that section are unchanged from defaults, except the one to point to my issue branch.
