### ISSUE TITLE
New versions of skimage.measure.regionprops  does not support values other than "rc" for the "coordinates" argument

### ISSUE THREAD

**Issue by tintinpallya** [PMEAL/porespy#232]
There is an issue with the "chord_length_distribution" metric function. When I tried the example for chord length distribution, I get the error shown in the image below related to the function skimage.measure.regionprops used in the code. 

![image](https://user-images.githubusercontent.com/5710454/78666568-c6fd1d00-78d7-11ea-9064-0cf3ee70bf63.png)

I saw the other similar issue https://github.com/PMEAL/porespy/issues/100 that is shown as resolved but I still seem to have the problem.

**Comment by jgostick** [comment]
This is fixed in the dev branch, which we'll be merging to master VERY soon.  There are a few critical things we want to fix, pertaining to the network extraction code, and once that's done we'll release version 1.3.  In the meantime you can get the dev branch using git and github. 

Download repo to a folder on your computer
Open conda prompt and navigate to that location
Uninstall the existing porespy with ``pip uninstall porespy``
Then install the source version with ``pip install -e .``  
You then need to open a git client (I'm using fork these day), and 'checkout' the dev branch.

Now when you open spyder or jupyter it will find your source code installed version, which has the dev branch active and you'll be good to go.  

Hope that works for you.
