### ISSUE TITLE
Improve IPython examples

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#253]
Since we currently treat IPython notebooks as integration tests - thanks to `pytest-nbval` - it's important to make examples such that testing can be done effectively. 

Currently, `pytest-nbval` can't test figure outputs, but most out examples' outputs are matplotlib figures. This is OK, but we can improve the testing quality by simply sprinkling some meaningful print statements here and there such as printing average concentration, permeability, or whatever's relevant to that particular example.

The reason I'm bringing this up is that as you might have noticed, we have too many cells that begin with `#NBVAL_IGNORE_OUTPUT`, which essentially bypasses the testing, and there are multiple examples that are essentially either not tested at all or minimally tested.

`pytest-nbval` is a great tool and we shouldn't miss this opportunity of easy integration testing as it's unlikely that we write separate integration tests anytime soon (if at all, and for good reason).

**Comment by jgostick** [comment]
I just added yet more of these, because of deprecation warnings

**Comment by jgostick** [comment]
I'm not sure I agree with this actually.  The reason that we use the #NBVAL_IGNORE is because some functions output progress and other info about the function, which changes on each run.  So the test runs, it just doesn't check the output.  If the cell were to actually fail then the testing would notify us.  In fact, I think we could tell ``pytest-nbval`` to ignore ALL output by default since the printouts of the functions are not important.  Beside, no many how many places we fix this, we still have to ignore all the matplotlib ``imshow`` outputs.

**Comment by jgostick** [comment]
This is done right @ma-sadeghi ?

**Comment by ma-sadeghi** [comment]
@jgostick no, I only did it for `porespy`. I'll take care of it asap.

**Comment by jgostick** [comment]
This is the porespy repo
