### ISSUE TITLE
SNOW is consuming too much memory maybe?

### ISSUE THREAD

**Issue by ma-sadeghi** [PMEAL/porespy#309]
I just ran SNOW parallel on a 2000^3 image and it took 215GB of memory to complete. That seems to be a bit too high as storing a 2000^3 float array takes ~64GB, which is almost a quarter. It might be worth digging into it.

@Zohaib-Atiq @jgostick

**Comment by Zohaib-Atiq** [comment]
@ma-sadeghi  are you using jupyter notebook to run you simulations? Also is 215 GB memory of output image or is this the maximum memory used while running the code?

**Comment by ma-sadeghi** [comment]
> @ma-sadeghi are you using jupyter notebook to run you simulations?

No, terminal

> Also is 215 GB memory of output image or is this the maximum memory used while running the code?

No, it was very consistent, although initially it was much lower, but soon it skyrocketed to 200GB+.

**Comment by ma-sadeghi** [comment]
One more thing I noticed: Even on a relatively small image, such as 1000^3, the memory usage skyrockets to 200GB+ if run on multiple phases (4 in my experience).

I don't exactly know the internals of SNOW, so I can't comment on whether or not this memory requirement is algorithmic, i.e. the algorithm can't do better in terms of memory efficiency. @Zohaib-Atiq @jgostick Any idea on this?

**Comment by vasudevanv** [comment]
I have noticed this issue as well. Although in my case 1000^3 seems to run without problems on a machine with 192 GB RAM and lower sizes seem to be scaling as expected. But larger than 1000^3 the RAM skyrockets as observed by @ma-sadeghi

**Comment by ma-sadeghi** [comment]
@vasudevanv Are you doing single phase extraction?

**Comment by Zohaib-Atiq** [comment]
@Amin are you using SNOW_parallel for multiple phase extraction. As far as I know It is currently for single phase. Are you doing any customization in snow_partitioning_n or you have separate custom code to extract multiple phases?

**Comment by vasudevanv** [comment]
Yes, mainly single phase extraction. Tagging @1minus1 here.

**Comment by ma-sadeghi** [comment]
> Yes, mainly single phase extraction.

That's why you didn't run out of memory for 1000^3. I did a 4-phase extraction and ran out of memory with 250GB RAM.

> @amin are you using SNOW_parallel for multiple phase extraction.

Yes, I'm using it for multiphase extraction. Basically, what I did is to replace the call to `snow_partitioning` with `snow_partioning_parallel` in `snow_partitioning_n` method. 

But the memory issue is not bound to the parallel version, I also tried the regular SNOW and still ran out of memory.

**Comment by Zohaib-Atiq** [comment]
@Amin regular snow RAM consumption will be 7.5 times more than the input image memory.  So if your input image is 64 GB then it will take 64 * 7.5 = 480 GB ram to perform watershed segmentation. That's why regular snow cannot segment above 1250 *3 image. SNOW parallel on the other hand divides the image into 1000**3 or 500**3 chunks depending upon the value of div number. So if 64 GB image is divided into eight 8GB chunks then each chunk will take 56GB ram during segmentation. Depending upon how many cores you are using all chunks memory processing in same time will add up. May be in your case 4 chunks are processing at same time as per above calculations. So 2000^3 image is expected to take that much RAM. If you want to reduce the RAM more then run SNOW_parallel in serial mode and also after you get the segmentation save it as tiff file and clear your console it will wash away all the memory if it is still there. Ideally after doing this your workstation should take 64GB ram if only segmented image is loaded again.

**Comment by ma-sadeghi** [comment]
> @amin regular snow RAM consumption will be 7.5 times more than the input image memory. So if your input image is 64 GB then it will take 64 * 7.5 = 480 GB ram to perform watershed segmentation. That's why regular snow cannot segment above 1250 *3 image. SNOW parallel on the other hand divides the image into 1000**3 or 500**3 chunks depending upon the value of div number. So if 64 GB image is divided into eight 8GB chunks then each chunk will take 56GB ram during segmentation. Depending upon how many cores you are using all chunks memory processing in same time will add up. May be in your case 4 chunks are processing at same time as per above calculations. So 2000^3 image is expected to take that much RAM. If you want to reduce the RAM more then run SNOW_parallel in serial mode and also after you get the segmentation save it as tiff file and clear your console it will wash away all the memory if it is still there. Ideally after doing this your workstation should take 64GB ram if only segmented image is loaded again.

Is it 7 times for each phase? Also, is there a way to make it more memory-efficient? One more thing: The input image is boolean, so a 2000^3 image actually takes up 8GB, right?

**Comment by jgostick** [comment]
i think this is related to the ``make_contiguous`` func which we've now fixed
