### ISSUE TITLE
Tortuosity diffusive less than 1

### ISSUE THREAD

**Issue by josephinoo** [PMEAL/porespy#495]
Hello, I have a query? I understand that the tortuosity must be greater than or equal to 1, to be specific when the porosity is 1, the tortuosity is 1, but use these lines of code, the result is less than 1. I'm in right or wrong?.

![Captura de Pantalla 2021-04-16 a la(s) 01 48 02](https://user-images.githubusercontent.com/46098690/114984041-ecabf300-9e56-11eb-953d-9b503157dd7c.png)
![Captura de Pantalla 2021-04-16 a la(s) 01 49 21](https://user-images.githubusercontent.com/46098690/114984046-eddd2000-9e56-11eb-8850-09f7f0600598.png)

**Comment by jgostick** [comment]
Interesting...I think I know what's causing this.  We apply concentration BCs in the top and bottom row of pixels in the image, but use the entire image length as the domain length.  But because the first and last pixels are already filled, diffusion does not need to occur into these.  We find the tau as DAB/DEFF, so we should probably scale this by Lx/(Lx-1).  This would give EXACTLY 1 for your 0.975 value, and 1.02 for your 0.997 value, which both make sense.  If you use a larger domain, this error become negligible, and 40-cubed is probably too small anyway.  Nonetheless, I will fix this asap...we're doing a bunch of changes as we move to V2.0, so it will be included in there.
