### ISSUE TITLE
Add handling of anisotropic voxel_size

### ISSUE THREAD

**Issue by TomTranter** [PMEAL/porespy#71]
Tomography data often has lower resolution in the stack direction than the in-plane. This is not handled in network extraction, consequently volumes and distances are going to be underestimated. Not sure it would be a straight-forward fix. Is there also an anisotropic distance transform out there?

**Comment by mdrkok** [comment]
it could be probably implemented with a homemade distance transform function, I have one laying around but it will need some work, i can have a crack at it

**Comment by TomTranter** [comment]
@mdrkok If you have a problem that this will solve then go for it. I think micro CT should be fine but FIB-SEM not. A work around would be to increase the number of pixels by copying the planes in stack direction. @jgostick is it reasonable to assume that voxel_size applies in all 3 directions and let the users figure out what to do? I identified this issue when looking at dragonfly as they allow pixel size to be different in all 3 directions so there may be problems with our plugins.

**Comment by mdrkok** [comment]
@TomTranter I'll have a go, also the io vtk funcs handle different spatial resoutions but I dont know about anything else

**Comment by ma-sadeghi** [comment]
@mdrkok You might find [this](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.morphology.distance_transform_edt.html) useful. In `scipy`'s `distance_transform_edt` (which is used in SNOW), you can pass `sampling` as an optional argument. The docs define `sampling` as the grid spacing, which might be the voxel anisotropy. I haven't looked at it, so it might as well be something totally different.

**Comment by mdrkok** [comment]
@TomTranter I just looked at it, its exactly what we need so that's good!

**Comment by mdrkok** [comment]
@ma-sadeghi oops, tagged the wrong person

**Comment by jgostick** [comment]
The problem is that we could *never* mange to implement this consistently in all functions.  I actually had an email last week regarding this question, and my reply was to use the ``scipy.ndimage.zoom`` function to expand the image in the missing dimension.  For instance, if you had an image with resolution of 2.5 x 2.5 x 10.0 um per voxel, you can use ``zoom`` as follows:

``` python
>>> im.shape
[100, 100, 100]
>>> import scipy.ndimage as spim
>>> im = spim.zoom(input=im, zoom=[1, 1, 8], order=0)
>>>im.shape
[100, 100, 800]

```

I hate to say no, but I think this will be the only way for us to truly and completely support this.  I even think we should add an example to the repo titled "Dealing with anisotropic voxel sizes", and showing the above code!
