### ISSUE TITLE
fill blind pores and trim floating solids do the same thing

### ISSUE THREAD

**Issue by mdrkok** [PMEAL/porespy#86]

**Comment by Zohaib-Atiq** [comment]
`trim_floating_solids` was made to remove floating solids from image. It is also used in `trim_non_percolating_paths` function. 
I agree that they will currently output the same thing and it is because of a bug inside `trim_floating_solids`. So line `im[holes] = True` should be `im[holes] = False`. Which means also a small change in `trim_non_percolating_paths`. I will do it and push the changes if all agree.

**Comment by Zohaib-Atiq** [comment]
![figure_1](https://user-images.githubusercontent.com/30351879/48921590-b8db6780-ee6e-11e8-9cae-83e1fc167d88.png)

**Comment by Zohaib-Atiq** [comment]
Ignore my above comments. @mdrkok these two functions are behaving differently with the current implementation. They look the same but have a different meaning. The purple is the solid phase with zero's label.

**Comment by Zohaib-Atiq** [comment]
While doing this test I also observed one thing. When we run these function the input image also changes.
For example when we do 
`im_fill_blind_pores = ps.filters.fill_blind_pores(im)`
Check
`plt.imshow(im)`
`plt.imshow(im_im_fill_blind_pores)`
gives same image. So I think a copy of image should be used to mask it with holes and then we should return masked copy as output. like

`def fill_blind_pores(im):
      holes = find_disconnected_voxels(im)
      new_im = im.copy()
      new_im[holes] = False
      return new_im`

**Comment by jgostick** [comment]
It seems the functions work ok, but the issue about not copying the input is a problem.  I will open a separate issue about that.
