### ISSUE TITLE
norm_to_uniform seems to slightly off

### ISSUE THREAD

**Issue by jgostick** [PMEAL/porespy#88]
When passing a gaussian blurred image, the returned image does not quite have a uniform distribution.  Not sure why...the error is small, but should be investigated.

**Comment by mdrkok** [comment]
The function actually works fine, it seems as blobiness gets low (<1) the pores get very large and it becomes difficult to make the distribution uniform due to the coarseness of the gaussian filter, in really large (or 3D ) images it also seems to be a problem for very high blobiness (>5). I don't think anything needs to be done
